
    alter table if exists collaborator_projects
       drop constraint if exists FK5kpa0x61428eivx39w4c216h;
    alter table if exists collaborator_projects
       drop constraint if exists FKm4db4bcau4iu453d13goewr8m;
    alter table if exists collaborator_skills
       drop constraint if exists FKbb5rbvrsi0m43gjn3i5qvkuh;
    alter table if exists collaborator_skills
       drop constraint if exists FK3cyrlff064tuvekjxx7okhbmm;
    alter table if exists participation
       drop constraint if exists FKi29knmhldnxgrbqv72csehpru;
    alter table if exists participation
       drop constraint if exists FKs0yblthwqvmld18g7wga85l7v;
    alter table if exists project
       drop constraint if exists FK8nw995uro0115f1go0dmrtn2d;
    alter table if exists project_assignees
       drop constraint if exists FKtph20c9xnww4jlncwhs4jlgra;
    alter table if exists project_assignees
       drop constraint if exists FKecvqetfhr49y3iavrwu3x4nyq;
    alter table if exists task
       drop constraint if exists FKk8qrwowg31kx7hp93sru1pdqa;
    alter table if exists task_assignees
       drop constraint if exists FKpaw716f39pnoirqew86kkyc3s;
    alter table if exists task_assignees
       drop constraint if exists FKo4yer4djkjpmp3hrghfn0hh9 ;
    drop table if exists client cascade;
    drop table if exists collaborator cascade;
    drop table if exists collaborator_projects cascade;
    drop table if exists collaborator_skills cascade;
    drop table if exists participation cascade ;
    drop table if exists project cascade;
    drop table if exists project_assignees cascade;
    drop table if exists skill cascade ;
    drop table if exists task cascade;
    drop table if exists task_assignees cascade;
    create table client (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        phone_number varchar(255),
        primary key (id)
    );
    create table collaborator (
        is_admin boolean not null,
        join_date date,
        id bigint generated by default as identity,
        avatar_url varchar(255),
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        primary key (id)
    );
    create table collaborator_projects (
        collaborator_id bigint not null,
        projects_id bigint not null unique,
        primary key (collaborator_id, projects_id)
    );
    create table collaborator_skills (
        collaborator_id bigint not null,
        skills_id bigint not null,
        primary key (collaborator_id, skills_id)
    );
    create table participation (
        collaborator_id bigint,
        id bigint generated by default as identity,
        project_id bigint,
        roles smallint array,
        primary key (id)
    );
    create table project (
        status smallint check (status between 0 and 2),
        client_id bigint,
        end timestamp(6),
        id bigint generated by default as identity,
        start timestamp(6),
        description varchar(255),
        title varchar(255),
        primary key (id)
    );
    create table project_assignees (
        assignees_id bigint not null,
        project_id bigint not null,
        primary key (assignees_id, project_id)
    );
    create table skill (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );
    create table task (
        status smallint check (status between 0 and 2),
        deadline timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        description varchar(255),
        title varchar(255),
        primary key (id)
    );
    create table task_assignees (
        assignees_id bigint not null,
        task_id bigint not null,
        primary key (assignees_id, task_id)
    );
    alter table if exists collaborator_projects
       add constraint FK5kpa0x61428eivx39w4c216h
       foreign key (projects_id)
       references participation;
    alter table if exists collaborator_projects
       add constraint FKm4db4bcau4iu453d13goewr8m
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists collaborator_skills
       add constraint FKbb5rbvrsi0m43gjn3i5qvkuh
       foreign key (skills_id)
       references skill;
    alter table if exists collaborator_skills
       add constraint FK3cyrlff064tuvekjxx7okhbmm
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists participation
       add constraint FKi29knmhldnxgrbqv72csehpru
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists participation
       add constraint FKs0yblthwqvmld18g7wga85l7v
       foreign key (project_id)
       references project;
    alter table if exists project
       add constraint FK8nw995uro0115f1go0dmrtn2d
       foreign key (client_id)
       references client;
    alter table if exists project_assignees
       add constraint FKtph20c9xnww4jlncwhs4jlgra
       foreign key (assignees_id)
       references participation;
    alter table if exists project_assignees
       add constraint FKecvqetfhr49y3iavrwu3x4nyq
       foreign key (project_id)
       references project;
    alter table if exists task
       add constraint FKk8qrwowg31kx7hp93sru1pdqa
       foreign key (project_id)
       references project;
    alter table if exists task_assignees
       add constraint FKpaw716f39pnoirqew86kkyc3s
       foreign key (assignees_id)
       references collaborator;
    alter table if exists task_assignees
       add constraint FKo4yer4djkjpmp3hrghfn0hh9
       foreign key (task_id)
       references task
