alter table if exists collaborator_projects
    drop constraint FK5kpa0x61428eivx39w4c216h;
alter table if exists collaborator_projects
    drop constraint FKm4db4bcau4iu453d13goewr8m;
alter table if exists collaborator_skills
    drop constraint FKbb5rbvrsi0m43gjn3i5qvkuh;
alter table if exists collaborator_skills
    drop constraint FK3cyrlff064tuvekjxx7okhbmm;
alter table if exists participation
    drop constraint FKi29knmhldnxgrbqv72csehpru;
alter table if exists participation
    drop constraint FKs0yblthwqvmld18g7wga85l7v;
alter table if exists project
    drop constraint FK8nw995uro0115f1go0dmrtn2d;
alter table if exists project_assignees
    drop constraint FKtph20c9xnww4jlncwhs4jlgra;
alter table if exists project_assignees
    drop constraint FKecvqetfhr49y3iavrwu3x4nyq;
alter table if exists task
    drop constraint FKk8qrwowg31kx7hp93sru1pdqa;
alter table if exists task_assignees
    drop constraint FKpaw716f39pnoirqew86kkyc3s;
alter table if exists task_assignees
    drop constraint FKo4yer4djkjpmp3hrghfn0hh9;

    create table if not exists client (
        id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        phone_number varchar(255),
        primary key (id)
    );
    alter table client owner to "unitrack-admin";

    create table if not exists collaborator (
        is_admin boolean not null,
        join_date date,
        id bigint generated by default as identity,
        avatar_url varchar(255),
        email varchar(255),
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        primary key (id)
    );
    alter table collaborator owner to "unitrack-admin";

    create table if not exists collaborator_projects (
        collaborator_id bigint not null,
        projects_id bigint not null unique,
        primary key (collaborator_id, projects_id)
    );
    alter table collaborator_projects owner to "unitrack-admin";

    create table if not exists collaborator_skills (
        collaborator_id bigint not null,
        skills_id bigint not null,
        primary key (collaborator_id, skills_id)
    );
    alter table collaborator_skills  owner to "unitrack-admin";

    create table if not exists participation (
        collaborator_id bigint,
        id bigint generated by default as identity,
        project_id bigint,
        roles smallint array,
        primary key (id)
    );
    alter table participation owner to "unitrack-admin";

    create table if not exists project (
        status smallint check (status between 0 and 2),
        client_id bigint,
        "end" timestamp(6),
        id bigint generated by default as identity,
        start timestamp(6),
        description varchar(255),
        title varchar(255),
        primary key (id)
    );
    alter table project owner to "unitrack-admin";

    create table if not exists project_assignees (
        assignees_id bigint not null,
        project_id bigint not null,
        primary key (assignees_id, project_id)
    );
    alter table project_assignees owner to "unitrack-admin";

    create table if not exists skill (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );
    alter table skill owner to "unitrack-admin";

    create table if not exists task (
        status smallint check (status between 0 and 2),
        deadline timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        description varchar(255),
        title varchar(255),
        primary key (id)
    );
    alter table task owner to "unitrack-admin";

    create table if not exists task_assignees (
        assignees_id bigint not null,
        task_id bigint not null,
        primary key (assignees_id, task_id)
    );
    alter table task_assignees owner to "unitrack-admin";

    alter table if exists collaborator_projects
       add constraint FK5kpa0x61428eivx39w4c216h
       foreign key (projects_id)
       references participation;
    alter table if exists collaborator_projects
       add constraint FKm4db4bcau4iu453d13goewr8m
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists collaborator_skills
       add constraint FKbb5rbvrsi0m43gjn3i5qvkuh
       foreign key (skills_id)
       references skill;
    alter table if exists collaborator_skills
       add constraint FK3cyrlff064tuvekjxx7okhbmm
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists participation
       add constraint FKi29knmhldnxgrbqv72csehpru
       foreign key (collaborator_id)
       references collaborator;
    alter table if exists participation
       add constraint FKs0yblthwqvmld18g7wga85l7v
       foreign key (project_id)
       references project;
    alter table if exists project
       add constraint FK8nw995uro0115f1go0dmrtn2d
       foreign key (client_id)
       references client;
    alter table if exists project_assignees
       add constraint FKtph20c9xnww4jlncwhs4jlgra
       foreign key (assignees_id)
       references participation;
    alter table if exists project_assignees
       add constraint FKecvqetfhr49y3iavrwu3x4nyq
       foreign key (project_id)
       references project;
    alter table if exists task
       add constraint FKk8qrwowg31kx7hp93sru1pdqa
       foreign key (project_id)
       references project;
    alter table if exists task_assignees
       add constraint FKpaw716f39pnoirqew86kkyc3s
       foreign key (assignees_id)
       references collaborator;
    alter table if exists task_assignees
       add constraint FKo4yer4djkjpmp3hrghfn0hh9
       foreign key (task_id)
       references task
