CREATE TABLE IF NOT EXISTS public.client
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.client
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.collaborator
(
    is_admin boolean NOT NULL,
    join_date date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    avatar_url character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT collaborator_pkey PRIMARY KEY (id),
    CONSTRAINT "UKf894lv4x22u8wxo7swqj0aad5" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.collaborator
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.project
(
    status smallint,
    client_id bigint,
    "end" date,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    start date,
    description character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT fk8nw995uro0115f1go0dmrtn2d FOREIGN KEY (client_id)
        REFERENCES public.client (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT project_status_check CHECK (status >= 0 AND status <= 2)
);

ALTER TABLE IF EXISTS public.project
    OWNER to "unitrack-admin";

CREATE TABLE IF NOT EXISTS public.participation
(
    collaborator_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint,
    roles smallint[],
    CONSTRAINT participation_pkey PRIMARY KEY (id),
    CONSTRAINT "FKivulb7mk2sp8qpxvdjhl1we1p" FOREIGN KEY (id)
        REFERENCES public.participation (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fki29knmhldnxgrbqv72csehpru FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fks0yblthwqvmld18g7wga85l7v FOREIGN KEY (project_id)
        REFERENCES public.project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.participation
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.collaborator_projects
(
    collaborator_id bigint NOT NULL,
    projects_id bigint NOT NULL,
    CONSTRAINT collaborator_projects_pkey PRIMARY KEY (collaborator_id, projects_id),
    CONSTRAINT collaborator_projects_projects_id_key UNIQUE (projects_id),
    CONSTRAINT fk5kpa0x61428eivx39w4c216h FOREIGN KEY (projects_id)
        REFERENCES public.participation (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkm4db4bcau4iu453d13goewr8m FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.collaborator_projects
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.skill
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT skill_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.skill
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.collaborator_skills
(
    collaborator_id bigint NOT NULL,
    skills_id bigint NOT NULL,
    CONSTRAINT collaborator_skills_pkey PRIMARY KEY (collaborator_id, skills_id),
    CONSTRAINT fk3cyrlff064tuvekjxx7okhbmm FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkbb5rbvrsi0m43gjn3i5qvkuh FOREIGN KEY (skills_id)
        REFERENCES public.skill (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



ALTER TABLE IF EXISTS public.collaborator_skills
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.task
(
    status smallint,
    deadline timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    project_id bigint,
    description character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    completed_on date,
    CONSTRAINT task_pkey PRIMARY KEY (id),
    CONSTRAINT fkk8qrwowg31kx7hp93sru1pdqa FOREIGN KEY (project_id)
        REFERENCES public.project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT task_status_check CHECK (status >= 0 AND status <= 2)
);



ALTER TABLE IF EXISTS public.task
    OWNER to "unitrack-admin";

CREATE TABLE IF NOT EXISTS public.collaborator_tasks
(
    collaborator_id bigint NOT NULL,
    tasks_id bigint NOT NULL,
    CONSTRAINT collaborator_tasks_pkey PRIMARY KEY (collaborator_id, tasks_id),
    CONSTRAINT "UK7m397dx2grmfqnlo9g444us2c" UNIQUE (tasks_id),
    CONSTRAINT "FKmvek4afh3ml1vhh5rchtvossn" FOREIGN KEY (tasks_id)
        REFERENCES public.task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FKslmycp9kgdwtoxdjoacnvfm9h" FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



ALTER TABLE IF EXISTS public.collaborator_tasks
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.comment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    text character varying(255) COLLATE pg_catalog."default",
    author_id bigint,
    reply_to_id bigint,
    task_id bigint,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT "FK5ar6qcbexv48hu8w8113wkuaq" FOREIGN KEY (author_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FKl4sla5eksptusfhw8xufqh4fo" FOREIGN KEY (reply_to_id)
        REFERENCES public.comment (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "FKovcgrykmnm8ya05nv4v1yqltx" FOREIGN KEY (task_id)
        REFERENCES public.task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



ALTER TABLE IF EXISTS public.comment
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.project_assignees
(
    assignees_id bigint NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT project_assignees_pkey PRIMARY KEY (assignees_id, project_id),
    CONSTRAINT fkecvqetfhr49y3iavrwu3x4nyq FOREIGN KEY (project_id)
        REFERENCES public.project (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fktph20c9xnww4jlncwhs4jlgra FOREIGN KEY (assignees_id)
        REFERENCES public.participation (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.project_assignees
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.project_tasks
(
    project_id bigint NOT NULL,
    tasks_id bigint NOT NULL,
    CONSTRAINT project_tasks_pkey PRIMARY KEY (project_id, tasks_id),
    CONSTRAINT "UKlfpqil1vs916bjmsrtmox0sqy" UNIQUE (tasks_id)
);

ALTER TABLE IF EXISTS public.project_tasks
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.recovery_code
(
    id bigint NOT NULL,
    code character varying(255) COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    collaborator_id bigint,
    CONSTRAINT recovery_code_pkey PRIMARY KEY (id),
    CONSTRAINT "UKohupmlela44o4vd6ylfnq05q" UNIQUE (collaborator_id),
    CONSTRAINT "FKfo4fttfuc9dmeanph8fohwui2" FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.recovery_code
    OWNER to "unitrack-admin";


CREATE TABLE IF NOT EXISTS public.task_assignees
(
    assignees_id bigint NOT NULL,
    task_id bigint NOT NULL,
    CONSTRAINT task_assignees_pkey PRIMARY KEY (assignees_id, task_id),
    CONSTRAINT fko4yer4djkjpmp3hrghfn0hh9 FOREIGN KEY (task_id)
        REFERENCES public.task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkpaw716f39pnoirqew86kkyc3s FOREIGN KEY (assignees_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.task_assignees
    OWNER to "unitrack-admin";