CREATE TABLE IF NOT EXISTS public.workspace
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    admin_id bigint,
    name character varying(255) COLLATE pg_catalog."default",
	CONSTRAINT workspace_pkey PRIMARY KEY (id),
    CONSTRAINT workspace_admin_fk FOREIGN KEY (admin_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.workspace
    OWNER to "unitrack-admin";

ALTER TABLE IF EXISTS public.collaborator
    ADD COLUMN workspace_id bigint;

ALTER TABLE IF EXISTS public.collaborator
    ADD CONSTRAINT collaborator_workspace_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
        ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.project
    ADD COLUMN workspace_id bigint;

ALTER TABLE IF EXISTS public.project
    ADD CONSTRAINT project_workspace_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
        ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.task
    ADD COLUMN workspace_id bigint;

ALTER TABLE IF EXISTS public.task
    ADD CONSTRAINT task_workspace_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
        ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.client
    ADD COLUMN workspace_id bigint;

ALTER TABLE IF EXISTS public.client
    ADD CONSTRAINT collaborator_workspace_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
        ON DELETE CASCADE;