CREATE TABLE IF NOT EXISTS public.collaborator_workspace
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    collaborator_id bigint,
    workspace_id bigint,
    is_admin boolean,
    CONSTRAINT collaborator_workspace_id PRIMARY KEY (id),
    CONSTRAINT collaborator_id_fk FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION,
    CONSTRAINT workspace_id_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.collaborator_workspace
    OWNER to "unitrack-admin";