CREATE TABLE IF NOT EXISTS public.message
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    text character varying(255) COLLATE pg_catalog."default",
    sender_id bigint NOT NULL,
    recipient_id bigint NOT NULL,
    sent_at timestamp,
    CONSTRAINT message_id PRIMARY KEY (id),
    CONSTRAINT message_sender_id_fk FOREIGN KEY (sender_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT recipient_id_fk FOREIGN KEY (recipient_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

ALTER TABLE IF EXISTS public.message
    OWNER to "unitrack-admin";