CREATE TABLE IF NOT EXISTS public.join_request
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    collaborator_id bigint NOT NULL,
    workspace_id bigint NOT NULL,
    expires_at timestamp,
    CONSTRAINT join_request_id PRIMARY KEY (id),
    CONSTRAINT join_request_collaborator_id_fk FOREIGN KEY (collaborator_id)
        REFERENCES public.collaborator (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    CONSTRAINT join_request_workspace_id_fk FOREIGN KEY (workspace_id)
        REFERENCES public.workspace (id) MATCH SIMPLE
            ON UPDATE CASCADE
            ON DELETE CASCADE
);

ALTER TABLE IF EXISTS public.join_request
    OWNER to "unitrack-admin";